[project]
name = "hierulz"
version = "0.1.0"
description = "Hierarchical decision rule models"
authors = [{name = "Your Name"}]
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"